import os
from neo4j import AsyncGraphDatabase
from dotenv import load_dotenv

load_dotenv()

# Load credentials from your .env file
NEO4J_URI = os.getenv("NEO4J_URI", "neo4j+s://29bf6e06.databases.neo4j.io")
NEO4J_USER = os.getenv("NEO4J_USER", "29bf6e06")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "Ju2TciNqoyqV5Gk1vMO5MeI7WebXI8BxnMMPk09YIwQ")

class Neo4jConnection:
    def __init__(self):
        # Initialize the asynchronous driver
        self.driver = AsyncGraphDatabase.driver(
            NEO4J_URI, 
            auth=(NEO4J_USER, NEO4J_PASSWORD),
            keep_alive=True,                # Send TCP keep-alive pings
            max_connection_lifetime=300,    # Recycle connections every 5 minutes before they die
            max_connection_pool_size=50,    # Cap the pool size
            connection_timeout=15.0
            )

    async def close(self):
        await self.driver.close()
    
    async def fetch_user_graph_facts(self) -> str:
        """
        Fetches all relationships connected to the User to inject into the ReAct prompt.
        Because Nexus is a personal agent, we fetch all facts radiating from the 'User' node.
        """
        async with self.driver.session() as session:
            # MATCH any node connected to the User and return the relationship and the target node
            query = """
            MATCH (u:User)-[r]->(target)
            RETURN type(r) AS relation, target.name AS target_name, labels(target)[0] AS target_type
            """
            result = await session.run(query)
            records = await result.data()

            if not records:
                return "No permanent facts established yet."

            # Format the raw graph data into human-readable sentences for the LLM
            facts = []
            for row in records:
                # Example output: "User IS_BUILDING Nexus (Type: Project)"
                facts.append(f"User {row['relation']} {row['target_name']} (Type: {row['target_type']})")

            return "\n".join(facts)

    async def execute_graph_update(self, graph_data: dict):
        """
        Takes the dictionary generated by the Open Ontology LLM schema
        and executes the MERGE commands safely using parameterized queries.
        """
        async with self.driver.session() as session:
            # 1. Merge all Nodes dynamically
            for node in graph_data.get("nodes", []):
                # The entity_type is dynamic (e.g., 'Dog', 'Technology')
                query = f"""
                MERGE (n:{node['entity_type']} {{name: $name}})
                """
                await session.run(query, name=node['entity_name'])

            # 2. Merge all Edges dynamically
            # UPDATE YOUR EDGE LOOP:
            if "edges" in graph_data:
                for edge in graph_data["edges"]:
                    
                    # 1. Safely extract IDs whether the LLM calls them "source" or "source_node"
                    source_id = edge.get("source") or edge.get("source_node")
                    target_id = edge.get("target") or edge.get("target_node")
                    
                    # Failsafe: if both are missing, skip this edge
                    if not source_id or not target_id:
                        continue

                    # 2. Grab and sanitize the relation
                    raw_relation = edge.get("relation", "RELATED_TO")
                    safe_relation = raw_relation.upper().replace(" ", "_").replace("-", "_")

                    # 3. Execute the Cypher query
                    query = f"""
                    MATCH (source {{id: $source_id}})
                    MATCH (target {{id: $target_id}})
                    MERGE (source)-[r:{safe_relation}]->(target)
                    """
                    await session.run(
                        query,
                        source_id=source_id,
                        target_id=target_id
                    )
                
# Instantiate a singleton client for FastAPI to use
neo4j_client = Neo4jConnection()