# app/graph/research_agent/nodes.py
from pydantic import SecretStr
from app.graph.supervisor_agent.state import BaseAgentState
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_groq import ChatGroq
from langchain_core.runnables import RunnableConfig
import os


groq_api_key = os.environ.get("GROQ_API_KEY")
if not groq_api_key:
    raise RuntimeError("GROQ_API_KEY is not set")

api_key = SecretStr(groq_api_key)
# Initialize worker LLM
research_llm = ChatGroq(
    model="meta-llama/llama-4-scout-17b-16e-instruct",
    temperature=0.2,
    api_key=api_key,
)


async def load_research_context_node(
    state: BaseAgentState, config: RunnableConfig
) -> dict:
    """Extracts its specific assignment and pulls live DB session context."""
    print(
        f"🔍 [RESEARCH:load_context] incoming delegated_tasks={state.get('delegated_tasks')!r}, "
        f"user_message={state.get('user_message')!r}"
    )

    # 1. Grab DB instance from runtime config
    db = config.get("configurable", {}).get("db")

    # 2. Grab task assigned by the Supervisor, fallback to raw message
    tasks = state.get("delegated_tasks", {})
    active_task = tasks.get("research", state.get("user_message", ""))

    print(f"🔍 [RESEARCH:load_context] resolved active_task={active_task!r}")
    return {"user_message": active_task}


async def call_research_llm_node(state: BaseAgentState) -> dict:
    """Executes the core instruction against the LLM."""
    active_task = state.get("user_message", "")
    print(f"🔍 [RESEARCH:call_llm] sending task to Groq -> {active_task!r}")

    system_prompt = SystemMessage(
        content="You are a sharp Research Assistant. Provide a detailed, concise summary of your findings."
    )
    user_prompt = HumanMessage(content=f"Research Task: {active_task}")

    response = await research_llm.ainvoke([system_prompt, user_prompt])

    print(
        f"🔍 [RESEARCH:call_llm] LLM responded -> {response.content[:200]!r}"
        f"{'...' if len(response.content) > 200 else ''}"
    )

    return {"messages": [response]}


async def export_research_results_node(state: BaseAgentState) -> dict:
    """Packages the final output safely into the shared global results dictionary."""
    all_messages = state.get("messages", [])
    print(f"🔍 [RESEARCH:export] total messages in state: {len(all_messages)}")

    # Get the last message generated by call_research_llm_node
    last_message = (
        state["messages"][-1].content if state.get("messages") else "No research found."
    )

    print(f"🔍 [RESEARCH:export] last_message used -> {str(last_message)[:200]!r}")

    output = {"worker_results": {"research": f"Research Results:\n{last_message}"}}
    print(f"🔍 [RESEARCH:export] returning -> {output!r}")

    # Return it wrapped in the custom merge_dicts reducer key
    return output
