# app/graph/research_agent/nodes.py
from pydantic import SecretStr
from app.graph.supervisor_agent.state import BaseAgentState
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_groq import ChatGroq
from langchain_core.runnables import RunnableConfig
import os

groq_api_key = os.environ.get("GROQ_API_KEY")
if not groq_api_key:
    raise RuntimeError("GROQ_API_KEY is not set")

api_key = SecretStr(groq_api_key)
# Initialize worker LLM
llm = ChatGroq(
    model="meta-llama/llama-4-scout-17b-16e-instruct",
    temperature=0.2,
    api_key=api_key,
)
_system_instructions = (
    "You are a friendly, conversational assistant handling casual banter, small talk, and direct questions.\n"
    "CRITICAL: You are provided with a rolling history summary and recent logs of this ongoing conversation. "
    "If the user asks about prior details, what you know about them, or their name, carefully scan the context history "
    "provided in the payload to answer accurately. Never claim you have no memory or that the conversation just started "
    "if details are present in the context window. Keep responses natural, direct, and concise."
)


# --- THE SINGLE SIMPLIFIED NODE ---
async def normal_agent_node(state: BaseAgentState) -> dict:
    """
    Handles fallback conversational responses by processing the token-optimized
    context window generated by the memory compaction engine.
    """
    # 🎯 OPTIMIZATION: Pull from our compressed context window instead of raw messages!
    optimized_history = state.get("context_window", [])

    # Prepend our specialized friendly system instruction to the context window
    llm_payload = [SystemMessage(content=_system_instructions)] + optimized_history

    try:
        # Non-blocking async invocation
        result = await llm.ainvoke(llm_payload)

        print(
            f"💬 [NORMAL AGENT] Handled friendly conversation: '{result.content[:50]}...'"
        )

        # Route directly into your direct_response key so the supervisor finalizes it smoothly
        return {"worker_results": {"normal": result.content}}
    except Exception as e:
        print(f"❌ Error in normal_agent_node execution: {e}")
        return {
            "direct_response": "Hey there! I ran into a small hiccup, how can I help you today?"
        }
